#!/bin/bash
# This is a simple client for interacting with the mc-signup daemon.
# Copyright (C) 2018 Robert Lowe <robert.lowe@maryvillecollege.edu>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#send a signup request
function send-request {
    echo "REQUEST:$1" | nc localhost 1819
}

#send a password request
function send-passwd {
    echo "PASSWD:$1:$2:$3" | nc localhost 1819
}

#echo invalid output
function send-invalid {
    (>&2 echo "INVALID COMMAND")
}


#run the appropriate command
case `basename $0` in
    "mc-signup-request")
	send-request $1
	;;
    "mc-signup-passwd")
	send-passwd $1 $2 $3
	;;
    *)
	send-invalid
	;;
esac
